apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
  nodeSelector:
    skyhook.io/pool: temp-general-purpose
