apiVersion: v1
kind: Pod
metadata:
  name: debug-aws-node-logs-grep-2
  namespace: kube-system
spec:
  nodeName: ip-10-0-9-142.us-west-2.compute.internal
  hostNetwork: true
  containers:
  - name: debug
    image: alpine
    command: ["sh", "-c", "grep -i 'AssignPrivateIpAddresses' /logs/ipamd.log | tail -n 20 && echo '---' && grep -i 'fail' /logs/ipamd.log | tail -n 20"]
    volumeMounts:
    - name: logs
      mountPath: "/logs"
  volumes:
  - name: logs
    hostPath:
      path: /var/log/aws-routed-eni
      type: Directory
  restartPolicy: Never
