serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: 
env:
  - name: AWS_REGION
    value: us-west-2
  - name: CLUSTER_NAME
    value: skyhook-accel-usw2-v69
  - name: ENVIRONMENT
    value: accel-usw2
