# AWS Secrets Manager Provider for Secrets Store CSI Helm Values
# Chart: secrets-store-csi-driver-provider-aws
# Repo: https://aws.github.io/secrets-store-csi-driver-provider-aws
# Version: 0.3.9

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 128Mi

tolerations:
  - operator: Exists

priorityClassName: system-node-critical

