# Secrets Store CSI Driver Helm Values
# Chart: secrets-store-csi-driver
# Repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
# Version: 1.4.5

enableSecretRotation: true
rotationPollInterval: 120s

syncSecret:
  enabled: true

windows:
  enabled: false

linux:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  tolerations:
    - operator: Exists
  priorityClassName: system-node-critical

logVerbosity: 0
logFormatJSON: true

serviceMonitor:
  enabled: false

